### ISSUE TITLE
issue when loading not just biomes 

### ISSUE THREAD

**Issue by youbannedmyotheraccount-thefatsparrow** [Apollounknowndev/lithostitched#3]
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Lithostitched' (lithostitched) 1.1.4a with version 1.0.0 or later.
More details:
	 - Mod 'Not Just Biomes' (njb) 1.2.1 requires version 1.0.0 or later of mod 'Lithostitched' (lithostitched), but only the wrong version is present: 1.1.4a!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

using the latest not just biomes and latest lithostitched version at the time of writing this and on version 1.20.2 

your welcome

**Comment by Apollounknowndev** [comment]
Not Just Biomes issue, will be fixed when it is updated next (soon:tm:)
